### ISSUE TITLE
Terraform 0.8.x compatability

### ISSUE THREAD

**Issue by cristobal23** [unifio/terraform-aws-openvpn#9]
Has anyone tried this module with terraform versions 0.8.x?  I got a invalid backslash escape sequence error on generate-certs/main.tf when using terraform 0.8.0
```
Error loading Terraform: Error downloading modules: module cert_generator: Error loading .terraform/modules/f128a8f9a1d97e66282f11571b6e3f70/generate-certs/main.tf: Error reading config for aws_iam_role_policy[s3_certs_rw]: parse error at 11:50: invalid backslash escape sequence
```

**Comment by disaac** [comment]
https://github.com/hashicorp/terraform/issues/8709 looks like related to the fix rolled out for this.

**Comment by cristobal23** [comment]
Thanks for the feedback @disaac! I tested the patch in #10 by running `bundle exec rake` as shown in circle.yml.
